### ISSUE TITLE
updated version of guide by anon

### ISSUE THREAD

**Issue by paenis** [hrtcat/hrtcat#1]
[catbox](https://files.catbox.moe/f2j7ba.pdf), [google docs](https://docs.google.com/document/d/1rK91wadC4c3Zh2CNfKAVuIsTYZsQagA0F_iMDVM7Wr4/edit)

posted on /lgbt/ by someone who may or may not be spiffy ([archive](https://archived.moe/lgbt/thread/31309044/#31312200)). it's not very widespread yet, but it might be worth putting a note about it in the section for the old guide

**Comment by hrtcat** [comment]
thank you! we'll take a look at this when we're able. if you'd like to open another PR, we'd love to have this added into the guide with just a note like "hey here's an updated version, it hasn't been reviewed yet #TODO". The PDF could get put in `/assets/PDFs/`. If not we'll try to tackle it on our next update. Might be a bit.
